permalink: /:categories:month/:title
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: true
url: http://maydogan.me
exclude:
        - Rakefile
        - Makefile
account: maydogan
archive: Son Girdiler
assets: /assets
author: Meltem AYDOĞAN
disqus: maydogan
email: meltem.aydogan@bil.omu.edu.tr
facebook: ~
feed: http://feeds.feedburner.com/maydogan
flickr: http://flickr.com/photos/maydogan
google: ~
googleanalyticsid: UA-23279313-1
domain: maydogan.me
googleplus: 118324661577121013170
gpg: ~
homeurl: http://maydogan.me
logo: /assets/19/19-normal-128x128.png
organization: 19
related: Diğer Girdiler
repository: maydogan.github.com
ribbon: GitHub'dayım
title: Meltem Aydoğan
twitter: http://twitter.com/maydogan_

navigator:
        0: Teknik Olmayan Yazılar
        1: Teknik Yazılar
        9: Kısa Notlar
